on: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10

    steps:
      - checkout

      - restore_cache:
          keys:
          - v0.2-dependencies-{{ checksum "env_cpu.yml" }}

      - run:
          name: Install conda
          command: |
            if [ ! -d "/home/circleci/miniconda" ]; then
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p "$HOME"/miniconda
              source /home/circleci/miniconda/etc/profile.d/conda.sh
              conda activate base
              # Conda configuration
              conda config --set always_yes yes --set auto_update_conda false
              # Update conda
              conda update conda
            fi
      - run:
          name: Create environment
          command: |
            if [ ! -d "/home/circleci/miniconda/envs/finetuna" ]; then
              source /home/circleci/miniconda/etc/profile.d/conda.sh
              conda activate base
              conda install -c conda-forge conda-merge
              conda env create -f env.cpu.yml
            fi
      - save_cache:
          paths:
            - /home/circleci/miniconda
          key: v0.2-dependencies-{{ checksum "env_cpu.yml" }}

      - run:
          name: Run black
          command: |
            source /home/circleci/miniconda/etc/profile.d/conda.sh
            conda activate finetuna
            pip install black
            black . --check
