on: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - restore_cache:
          keys:
          - v0.2-dependencies-{{ checksum "env_cpu.yml" }}

      - run:
          name: Install conda
          command: |
            if [ ! -d "/home/circleci/miniconda" ]; then
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p "$HOME"/miniconda
              source /home/circleci/miniconda/etc/profile.d/conda.sh
              conda activate base
              # Conda configuration
              conda config --set always_yes yes --set auto_update_conda false
              # Update conda
              conda update conda
            fi
      - run:
          name: Create environment
          command: |
            if [ ! -d "/home/circleci/miniconda/envs/al_mlp" ]; then
              source /home/circleci/miniconda/etc/profile.d/conda.sh
              conda activate base
              conda install -c conda-forge conda-merge
              wget https://raw.githubusercontent.com/ulissigroup/amptorch/master/env_cpu.yml -O env_amptorch_cpu.yml
              conda-merge env_amptorch_cpu.yml env_cpu.yml > env.yml
              conda env create -f env.yml
            fi
      - save_cache:
          paths:
            - /home/circleci/miniconda
          key: v0.2-dependencies-{{ checksum "env_cpu.yml" }}

      - run:
          name: Run black
          command: |
            source /home/circleci/miniconda/etc/profile.d/conda.sh
            conda activate al_mlp
            pip install black
            black . --check

      - run:
          name: Run tests
          command: |
            source /home/circleci/miniconda/etc/profile.d/conda.sh
            conda activate al_mlp
            pip install -e .
            pip install spglib
            OMP_NUM_THREADS=1 pytest al_mlp/tests/suites/light_suite.py
          no_output_timeout: 1.5h
